name: Deploy LFS to Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Используем актуальную версию v4
        with:
          lfs: true # Скачиваем само видео, а не ссылку

      - name: Checkout LFS objects
        run: git lfs pull # Принудительно вытягиваем файлы

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Публикуем текущую папку
